# Generated by Django 3.2.6 on 2022-04-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_etudiant_professeur'),
        ('semestre', '0002_niveau_filliere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeHoraire', models.IntegerField()),
                ('objectif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_module', models.CharField(max_length=200, null=True)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semestre.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant_Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsable', models.BooleanField()),
                ('annee_universitaire', models.DateField()),
                ('element_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.module'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='perequis',
            field=models.ManyToManyField(related_name='perequises', to='module.ElementModule'),
        ),
    ]
