# Generated by Django 3.2.6 on 2022-04-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='filliere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.filiere'),
        ),
    ]
